env = Environment()

env['APP_TARGET'] = 'MarkerCubeApp'
env['APP_SOURCES'] = ['MarkerCubeApp.cpp']
env['ASSETS'] = ['camera_para.dat', 'marker_cube.cfg']
env['DEBUG'] = 1

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

