env = Environment()

env['APP_TARGET'] = 'ArtkpApp'
env['APP_SOURCES'] = ['ArtkpApp.cpp']
env['ASSETS'] = ['camera_para.dat']
env['DEBUG'] = 0

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

